# Generated by Django 2.2.6 on 2019-11-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(max_length=10),
        ),
    ]
