# Generated by Django 2.2.6 on 2019-11-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191101_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(),
        ),
    ]
